In [0]:
#IMPORTING REQUIRED LIBRARIES
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [0]:
#Read CSV FILE
df = pd.read_csv("https://raw.githubusercontent.com/codeheroku/Introduction-to-Machine-Learning/master/Building%20a%20Movie%20Recommendation%20Engine/movie_dataset.csv")
print(df.head(5))

   index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]


In [0]:
#SELECT FEATURES
features = ['keywords','cast','genres','director']

In [0]:
#CREATE A COLUMN IN DF WHICH COMBINES ALL SELECTED FEATURES
df["combined_fetures"] = df["keywords"].astype(str) + " " + df["cast"].astype(str) + " " + df["genres"].astype(str) + " " + df["director"].astype(str)
df.fillna(" ",inplace=True)
print(df.combined_fetures)  

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6 Dan...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799     Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800    date love at first sight narration investigati...
4801     Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802    obsession camcorder crush dream girl Drew Barr...
Name: combined_fetures, Length: 4803, dtype: object


In [0]:
#CREAT A COUNT MATRIX FROM THIS NEW COMBINED COLUMN
cv = CountVectorizer()
count_matrix = cv.fit_transform(df.combined_fetures)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
#COMPUTE THE COSINE SIMILARITY BASED ON THE count_matrix
similarity = cosine_similarity(count_matrix)

movie_users_like = "Avatar"

In [0]:
#GET INDEX OF THIS MOVIE FROM IT'S TITLE
# title = "Avatar"
# df[df["title"] == title]["index"].values[0]
def get_title_from_index(title):
	return df[df["title"] == title]["index"].values[0]
# def get_index_from_title(title):
#     try:
#         return df[df.title == title]["index"].values[0]
#     except IndexError:
#         return None
movie_index = get_title_from_index("Avatar")

In [0]:
#GET A LIST OF SIMILAR MOVIES IN DESCENDING ORDER OF SIMILARITY SCORE
similar_movies = list(enumerate(similarity[movie_index]))
similar_sorted_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

In [0]:
#PRINT TITLES OF FIRST 50 MOVIES
def get_index_from_title(index):
	return df[df["index"] == index]["title"].values[0]

i = 0
for element in similar_sorted_movies:
  print(get_index_from_title(element[0]))
  i = i+1
  if i>50:
      break

Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
Alien
Lockout
Jason X
The Helix... Loaded
Moonraker
Planet of the Apes
Galaxy Quest
Gravity
Alien³
Jupiter Ascending
The Wolverine
Silent Running
Zathura: A Space Adventure
Trekkies
Cargo
Wing Commander
Star Trek
Lost in Space
Babylon A.D.
The Fifth Element
Oblivion
Titan A.E.
AVP: Alien vs. Predator
The Empire Strikes Back
Dragonball Evolution
Superman Returns
Divergent
John Carter
The Black Hole
The Ice Pirates
Memoirs of an Invisible Man
Starship Troopers
The Astronaut's Wife
Machete Kills
Soldier
The Abyss
Damnation Alley
Men in Black
Space Cowboys
Space Dogs
The Time Machine
Sheena
Captain America: Civil War
Star Trek: Insurrection
Oz: The Great and Powerful
